# Root logger option
rootLogger.level=DEBUG
rootLogger.appenderRefs=STDOUT, FILE
rootLogger.appenderRef.STDOUT.ref=STDOUT
rootLogger.appenderRef.FILE.ref=FILE

# Direct log messages to stdout
appender.stdout.type=Console
appender.stdout.name=STDOUT
appender.stdout.target=SYSTEM_OUT
appender.stdout.layout.type=PatternLayout
appender.stdout.layout.pattern=%d{dd-MM-yyyy HH:mm:ss} %-5p %c{1}:%L - %m%n

# Direct log messages to a log file
appender.file.type=RollingFile
appender.file.name=FILE
appender.file.fileName=./logs/ogv.log
appender.file.filePattern=./logs/ogv-%d{MM-dd-yyyy}-%i.log.gz

appender.file.layout.type=PatternLayout
appender.file.layout.pattern=%d{dd-MM-yyyy HH:mm:ss} %-5p %c{1}:%L - %m%n

appender.file.policies.type=Policies
appender.file.policies.size.type=SizeBasedTriggeringPolicy
appender.file.policies.size.size=10MB

appender.file.strategy.type=DefaultRolloverStrategy
appender.file.strategy.max=10